services:
  sync-grafana:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      GF_SERVER_PROTOCOL: http
      GF_SERVER_DOMAIN: https://monitoring.usesync.ai
      GF_SERVER_ROOT_URL: https://monitoring.usesync.ai
      GF_SERVER_ENABLE_GZIP: true
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: db:5432
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: grafana
      GF_DATABASE_PASSWORD: password
      GF_AUTH_GOOGLE_ENABLED: true
      GF_AUTH_GOOGLE_ALLOW_SIGN_UP: true
      GF_AUTH_GOOGLE_AUTO_LOGIN: false
      GF_AUTH_GOOGLE_CLIENT_ID: CLIENT_ID
      GF_AUTH_GOOGLE_CLIENT_SECRET: CLIENT_SECRET
      GF_AUTH_GOOGLE_ALLOWED_DOMAINS: usesync.ai
      GF_AUTH_GOOGLE_HOSTED_DOMAIN: usesync.ai
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: grafana
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U grafana" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
